{"name": "test_get_token", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\c5\\\\Desktop\\\\Project\\\\pytest\\\\api\\\\logger\\\\2023-05-08.txt'", "trace": "def test_get_token():\n        caseinfo = {\n            'url': '/api/user/phone/loginPassword',\n            'method': 'post',\n            'headers': {\n                'lang': 'zh-CN',\n                'content-type': 'application/x-www-form-urlencoded;charset=UTF-8'\n            },\n            'datas': {\n                'source': 1,\n                'ime': '97dd9609edd4c7bc52f36276c9cefd2b',\n                'password': 'qq111111',\n                'mobile': 18069776400\n            }\n        }\n        req = mobile_login(caseinfo)\n        data = {'token': req.json()['data']['token']}\n>       write_extract_yaml(data, file_name=\"/common/token.yml\")\n\nuser_api.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\utils\\yaml_util.py:25: in write_extract_yaml\n    LogUtil().set_log().info(\"缓存数据写入成功{}\".format(data))\n..\\utils\\log_util.py:46: in set_log\n    self.logger.addHandler(self.file_handler())\n..\\utils\\log_util.py:23: in file_handler\n    file_handler = logging.FileHandler(\nE:\\python\\lib\\logging\\__init__.py:1169: in __init__\n    StreamHandler.__init__(self, self._open())\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <[AttributeError(\"'FileHandler' object has no attribute 'level'\") raised in repr()] FileHandler object at 0x2401a0068c0>\n\n    def _open(self):\n        \"\"\"\n        Open the current base file with the (original) mode and encoding.\n        Return the resulting stream.\n        \"\"\"\n        open_func = self._builtin_open\n>       return open_func(self.baseFilename, self.mode,\n                         encoding=self.encoding, errors=self.errors)\nE       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\c5\\\\Desktop\\\\Project\\\\pytest\\\\api\\\\logger\\\\2023-05-08.txt'\n\nE:\\python\\lib\\logging\\__init__.py:1201: FileNotFoundError"}, "start": 1683533976040, "stop": 1683533977087, "uuid": "43374edd-0e21-41a7-9449-ac165f3d940e", "historyId": "bbdf080b46101cbbec6123715715a2fa", "testCaseId": "1b34c5ab6b95e0f71078f47300f20574", "fullName": "api.user_api#test_get_token", "labels": [{"name": "parentSuite", "value": "api"}, {"name": "suite", "value": "user_api"}, {"name": "host", "value": "DESKTOP-CM07T3T"}, {"name": "thread", "value": "12344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api.user_api"}]}